Development setup with docker compose
SecretSourceWeb/BikesAnonNode pull request #2
Opened 2021-06-15 12:52 UTC by manuhdez

The application has been containerized with docker in order to launch a local version easily without extra setup.

Services configured:
- backend (The actual app running with nodejs v15.0)
- mongodb (To persist the application data)

2021-06-15 16:01 UTC, tedsecretsource commented
`docker compose build` seems to work but `docker compose start` doesn't seem to do anything and `docker compose ps` shows that no containers are running, so, something is failing. I assume there are logs somewhere that would provide more info but meanwhile, docker desktop is rebuilding itself!

2021-06-15 16:04 UTC, tedsecretsource requested changes
I'm not seeing where we do `yarn` to install dependencies (although I don't think that that's the problem I'm having).

2021-06-15 16:04 UTC, tedsecretsource commented on docker-compose.yml
> +  mongodb:
Should this have a value, maybe just a dot?

2021-06-16 08:09 UTC, manuhdez commented on docker-compose.yml
> +  mongodb:
I read a couple of articles and it looks like you only need that reference but I haven't been able to properly test it.
I will be adding data into the database and test if the data persist within the container both with and without this reference.

2021-06-16 08:23 UTC, manuhdez commented
> `docker compose build` seems to work but `docker compose start` doesn't seem to do anything and `docker compose ps` shows that no containers are running, so, something is failing. I assume there are logs somewhere that would provide more info but meanwhile, docker desktop is rebuilding itself!

I think we might need to stick to `docker-compose up --build` for the first build and `docker-compose up -d` to launch the containers.

2021-06-17 08:46 UTC, manuhdez commented on docker-compose.yml
> +  mongodb:
As you can see [here](https://stackoverflow.com/a/64020164/10699118), declaring the volume like this is equivalent to run the command `docker volume create mongodb`, which lets docker to manage the volume automatically.

2021-06-17 10:05 UTC, merged